# Generated by Django 5.1.6 on 2025-04-03 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_order_created_at_remove_order_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='admin@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=25),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(default='admin', max_length=25),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
