# Generated by Django 5.1.6 on 2025-04-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employee_email_employee_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Utilities', 'Utilities'), ('Rent', 'Rent'), ('Salaries', 'Salaries'), ('Supplies', 'Supplies'), ('Maintenance', 'Maintenance'), ('Marketing', 'Marketing'), ('Insurance', 'Insurance'), ('Other', 'Other')], default='Other', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='FinancialReport',
        ),
    ]
